print('Enter the name of your cat:')
catName1 = input()
print('Enter the name of your cat:')
catName2 = input()
print('Enter the name of your cat:')
catName3 = input()
print('Enter the name of your cat:')
catName4 = input()
print('Enter the name of your cat:')
catName5 = input()
print('Enter the name of your cat:')
catName6 = input()
print('The cat names are:')
print(catName1 + ' ' + catName2 + ' ' + catName3 +
      ' ' + catName4 + ' ' + catName5 + ' ' + catName6)
